env                    = "staging"
project                = "Todo - Staging"
resource_group_name    = "devmobx-todo-staging-rg"
cosmosdb_account_name  = "devmobx-todo-staging-db"
cosmosdb_database_name = "TodoDataStaging"
